### ISSUE TITLE
Update broke wireless network

### ISSUE THREAD

**Issue by tomoqv** [calebccff/pmos-oneplus6#4]
uname -r yields the following: `5.11.0-postmarketos-qcom845
`
After an update yesterday (`apk update && apk upgrade`) and a reboot, my OP6 booted into PMOS without any wifi indicator or any wireless option available in settings. Also, the battery indicator shows only a question mark although the unit should be fully charged.

I have tried to restart the networkmanager from the cli, but still the same. There is no iwd option available from the shell.

Any other commands I can try to get it running?

**Comment by kcxt** [comment]
This happened because the kernel update removed the old kernel modules, those are uh, needed as they contain the drivers you need.

Updating the kernel is not supported with this flashable zips.

**Comment by kcxt** [comment]
Sorry, to offer some more clarity, updating the kernel on Android devices is a bit of a pain, everything has to be packed into a device specific boot image. PostmarketOS does do this for us, however it uses it's own initramfs which these flashable zips aren't compatible with.

We install the rootfs as a file on userdata, the stock initramfs doesn't know how to access this.

We are currently working on integrating this installer into postmarketOS, which will resolve all these issues, until then it's inadvisable to update the kernel as it will lead to errors like the one you're encountering, and won't actually work.

If you want to get updates your best bet is to follow the standard postmarketOS install guide and flash to the system partition of your inactive slot.

Sorry for the confusion and general lack of explanation in the README, these issues generally aren't obvious without a substantial amount of context.

**Comment by tomoqv** [comment]
Ok, thanks for the info. So, I should only update through the software store and not with apk upgrade then?

I am trying to reflash now with pmbootstrap as I did before, but I am getting some issues. E.g. this one:
`[16:53:43] ERROR: [Errno 2] No such file or directory: '/home/tomas/.local/var/pmbootstrap/chroot_rootfs_oneplus-enchilada/usr/share/kernel/sdm845/kernel.release'`

**Comment by tomoqv** [comment]
By the way, is there a way to roll back to the previous kernel in PMOS?
Thanks!

**Comment by kcxt** [comment]
> Ok, thanks for the info. So, I should only update through the software store and not with apk upgrade then?
> 
> I am trying to reflash now with pmbootstrap as I did before, but I am getting some issues. E.g. this one:
> `[16:53:43] ERROR: [Errno 2] No such file or directory: '/home/tomas/.local/var/pmbootstrap/chroot_rootfs_oneplus-enchilada/usr/share/kernel/sdm845/kernel.release'`

This issue has just been fixed, `pmbootstrap pull` and zap to make sure you get the latest package (linux-postmarketos-qcom-sdm845 should be version 5.12-r1).

The software center is just UI for APK, updating the kernel package WILL cause problem, irrelevant of how you do it.

You can probably roll back by installing the old kernel package again.

**Comment by tomoqv** [comment]
Trying again now, but the following step has been processing for 6-7 minutes now:
`[17:59:23] (native) build aarch64/linux-postmarketos-qcom-sdm845-5.12-r1.apk`
My computer is working at full load, but nothing seems to happen.

**Comment by kcxt** [comment]
> Trying again now, but the following step has been processing for 6-7 minutes now:
> `[17:59:23] (native) build aarch64/linux-postmarketos-qcom-sdm845-5.12-r1.apk`
> My computer is working at full load, but nothing seems to happen.

Sounds like it's compiling... `pmbootstrap log` shows verbose output.

**Comment by tomoqv** [comment]
Process ended with the following error:
```
[17:59:23] (native) build aarch64/linux-postmarketos-qcom-sdm845-5.12-r1.apk
[18:37:22] WARNING: device-oneplus-enchilada depends on rebuilt package(s) linux-postmarketos-qcom-sdm845 (use 'pmbootstrap build device-oneplus-enchilada --force' if necessary!)
[18:37:23] (rootfs_oneplus-enchilada) install postmarketos-base device-oneplus-enchilada device-oneplus-enchilada-nonfree-firmware calls chatty eog firefox-esr font-noto font-noto-emoji gedit gnome-calculator gnome-clocks gnome-contacts gnome-software kgx megapixels mobile-config-firefox nemo postmarketos-artwork-wallpapers postmarketos-hidden-desktop-entries postmarketos-tweaks postmarketos-welcome-gtk3 xdg-user-dirs xwayland postmarketos-ui-phosh nano neofetch lang musl-locales
[sudo] lösenord för tomas: 
[18:42:26] NOTE: The failed command's output is above the ^^^ line in the log file: /home/tomas/.local/var/pmbootstrap/log.txt
[18:42:26] ERROR: Command failed: % sudo mkfifo /home/tomas/.local/var/pmbootstrap/chroot_rootfs_oneplus-enchilada/tmp/apk_progress_fifo
[18:42:26] See also: <https://postmarketos.org/troubleshooting>
Run 'pmbootstrap log' for details.

```

**Comment by tomoqv** [comment]
Sorry to bother you again, but I am trying to get my OP6 back on track with PMOS. Phone still boots to PMOS and neofetch shows the following, but there is still no wireless settings available and battery icon shows '?'.
![bild](https://user-images.githubusercontent.com/13762919/118457743-5a6b6900-b6fa-11eb-9f96-73fb639a4df5.png)
I have been trying to flash a newly built kernel with pmbootstrap, but it doesn't seem to complete. Last time I also cleared the dtbo, but flashing the rootfs doesn't work.

I am able to access the phone through ssh.

Also attaching the pmbootstrap log.
[log.txt](https://github.com/calebccff/pmos-oneplus6/files/6492390/log.txt)

It also seems that slot a is broken. I haven't been able to enter recovery since I first installed PMOS.

Any help would be appreciated!

**Comment by kcxt** [comment]
Hi Tomas, once the dtbo has been erased, it will have to be restored again in order to boot any downstream kernels (twrp / Android).

Your current lack of WiFi on 5.12 is most likely due to missing kernel modules, as you flashed the 5.12 kernel but didn't deploy a new rootfs, maybe try uninstalling / reinstalling the kernel package (linux-postmarketos-qcom-sdm845).

Please can you follow the instructions on the README under "creating an issue" to obtain logs from the device and post them here.

Can you elaborate on "flashing the rootfs doesn't work"?

**Comment by tomoqv** [comment]
Computers are never totally predictable. I booted my OP6 into Fastboot Mode a couple of hours ago and has just let it sit and rest connected to my PC. Now, when I came back and ran `pmbootstrap flasher flash_rootfs --partition userdata` is just went through without issues. I followed up with `pmbootstrap flasher flash_kernel` and I am back in business! How strange is that?

Normally, doing the same thing over and over expecting a different result is considered stupid, lucky enough I am also stubborn :_).

Now I just need to reinstall some apps and log back into Firefox etc. and I am good to go!

**Comment by tomoqv** [comment]
Now the software center asks me to upgrade the Mainline kernel (linux-postmarket0s-qcom-sdm845). I guess this is what I should not do, right, because it will break wifi etc.?

I am not getting any software center though, what do I need to do to get it back? Can I hit the update button in the software center (not the one that says "Upgrade all")? Edit: Software back after a few reboots.
