### ISSUE TITLE
Stuck at empty kernel messages screen after update

### ISSUE THREAD

**Issue by Rubo3** [calebccff/pmos-oneplus6#6]
Hi, on a fresh install of this distribution I have updated every package, leaving for last `linux-postmarketos-qcom-sdm845`, then I rebooted, updated it from 5.11-r2 to 5.12.15-r0 and rebooted again. Now at boot the device is stuck on an empty kernel messages screen, the only things visible are the Tux row and underneath it the blinking cursor. I don't know where to start to try tackle this problem. Do you have any clue?

**Comment by kcxt** [comment]
hello, this install method is no longer recommended or supported, as installing kernel updates bricks the device - as you've seen.

Please follow one of the installation method mentioned on the device wiki page: https://wiki.postmarketos.org/wiki/OnePlus_6_(oneplus-enchilada)

Implementing proper support for a flashable ZIP is on the TODO list but unfortunately I don't have much time to work on it at the minute.

**Comment by Rubo3** [comment]
I see, thank you!
